name: reIndexer
channels:
  - Quantopian
  - defaults
dependencies:
  - alembic=0.7.7
  - asn1crypto=0.24.0
  - astroid=2.0.4
  - bcolz=0.12.1
  - blas=1.0
  - blosc=1.15.0
  - bottleneck=1.2.1
  - bzip2=1.0.6
  - ca-certificates=2019.1.23
  - certifi=2018.8.24
  - cffi=1.11.5
  - chardet=3.0.4
  - click=6.7
  - contextlib2=0.5.5
  - cryptography=2.3.1
  - cyordereddict=0.2.2
  - cython=0.28.5
  - decorator=4.4.0
  - empyrical=0.5.0
  - hdf5=1.10.2
  - icu=58.2
  - idna=2.7
  - intel-openmp=2019.3
  - intervaltree=2.1.0
  - isort=4.3.4
  - lazy-object-proxy=1.3.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libxml2=2.9.9
  - libxslt=1.1.33
  - logbook=0.12.5
  - lru-dict=1.1.4
  - lxml=4.2.5
  - lzo=2.10
  - markupsafe=1.0
  - mccabe=0.6.1
  - mkl=2018.0.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - multipledispatch=0.6.0
  - networkx=1.11
  - numexpr=2.6.1
  - numpy=1.14.6
  - numpy-base=1.14.6
  - openssl=1.0.2r
  - pandas=0.22.0
  - pandas-datareader=0.6.0
  - patsy=0.5.0
  - pycparser=2.19
  - pylint=2.1.1
  - pyopenssl=18.0.0
  - pysocks=1.6.8
  - pytables=3.4.4
  - python=3.5.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - requests=2.19.1
  - requests-file=1.4.3
  - requests-ftp=0.3.1
  - scipy=1.1.0
  - setuptools=40.2.0
  - six=1.11.0
  - snappy=1.1.7
  - sortedcontainers=2.0.5
  - sqlalchemy=1.2.11
  - sqlite=3.27.2
  - statsmodels=0.9.0
  - tk=8.6.8
  - toolz=0.9.0
  - trading-calendars=1.5.1
  - typed-ast=1.1.0
  - urllib3=1.23
  - wheel=0.31.1
  - wrapt=1.10.11
  - xz=5.2.4
  - zipline=1.3.0
  - zlib=1.2.11
  - pip:
    - et-xmlfile==1.0.1
    - jdcal==1.4.1
    - mako==1.0.7
    - openpyxl==2.6.2
    - pip==19.0.3
    - ta-lib==0.4.17

